# .streamlit/secrets.toml
[openai]
api_key = "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"
